app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix: /admin
login:
    path: /login
    defaults : {_controller:AppBundle:User:login}

login_check:
    path: /login_check
    defaults : {_controller:AppBundle:User:login_check}

logout:
    path: /logout
    defaults : {_controller:AppBundle:User:logout}