security:

    encoders:
        AppBundle\Entity\User: bcrypt

    providers:
        my_provider:
            entity: { class: AppBundle:User, property: nomUtilisateur }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true

            provider: my_provider

            form_login:
                login_path: login
                check_path: login_check
                default_target_path: homepage
            logout:
                path:   /logout

    access_control:

        - { path: ^/admin/user/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        # Users access
        - { path: ^/admin, roles: ROLE_ADMIN }